apiVersion: v1
kind: Pod
metadata:
  name: configvars
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: ConfigMap

# apiVersion: v1
# kind: Pod
# metadata:
#   name: config-map-demo
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     envFrom:
#     - configMapRef:
#         name: pod-config