apiVersion: v1
kind: Pod
metadata:
 name: first-pod
 labels: 
   environment: dev
   project:  Aviva
   component: frontend
 annotations:
   google: "https/google.com"
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "64Mi"
      cpu: "100M"
    limits:
      memory: "120Mi"
      cpu: "150M"
